=== newrelic/entity-definitions/validator/schemas/dashboard-schema-v1.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "dashboard-schema-v1",
  "type": "object",
  "title": "Dashboard template schema",
  "description": "Schema used to verify that a given dashboard template is valid.",
  "required": [
    "name",
    "pages"
  ],
  "properties": {
    "name": {
      "$id": "#/properties/name",
      "type": "string",
      "title": "The name of the dashboard"
    },
    "description": {
      "$id": "#/properties/description",
      "type": ["string", "null"],
      "title": "Description of the dashboard contents"
    },
    "permissions": {
      "$id": "#/properties/permissions",
      "type": "string",
      "title": "The permissions of the dashboard"
    },
    "pages": {
      "$id": "#/properties/pages",
      "type": "array",
      "title": "The pages that form the dashboard",
      "minItems": 1,
      "maxItems": 1,
      "items": {
        "$id": "#/properties/pages/items",
        "anyOf": [{
          "$id": "#/properties/pages/items/anyOf/0",
          "type": "object",
          "title": "The contents of a dashboard's page",
          "required": [
            "name",
            "widgets"
          ],
          "properties": {
            "name": {
              "$id": "#/properties/pages/items/anyOf/0/properties/name",
              "type": "string",
              "title": "The name of the dashboard page"
            },
            "description": {
              "$id": "#/properties/pages/items/anyOf/0/properties/description",
              "type": ["string", "null"],
              "title": "Description of the dashboard's page contents"
            },
            "widgets": {
              "$id": "#/properties/pages/items/anyOf/0/properties/widgets",
              "type": "array",
              "title": "The widgets that form the dashboard",
              "items": {
                "$id": "#/properties/pages/items/anyOf/0/properties/widgets/items",
                "anyOf": [{
                  "$id": "#/properties/pages/items/anyOf/0/properties/widgets/items/anyOf/0",
                  "type": "object",
                  "title": "The widget definition",
                  "required": [
                    "visualization",
                    "layout",
                    "title",
                    "rawConfiguration"
                  ],
                  "properties": {
                    "linkedEntityGuids": {
                      "$id": "#/properties/pages/items/anyOf/0/properties/widgets/items/anyOf/0/properties/linkedEntityGuids",
                      "type": "null",
                      "title": "The linked entity guids",
                      "description": "Unsupported guids of linked entities. Only allowed with a null value. The dashboard exporter will always provide the field, so it's quite common that it is present. It is inconvenient to remove those fields manually, so it's syntactically allowed but only with a null value.",
                      "const": null
                    },
                    "visualization": {
                      "$id": "#/properties/pages/items/anyOf/0/properties/widgets/items/anyOf/0/properties/visualization",
                      "type": "object",
                      "title": "The visualization type",
                      "required": [
                        "id"
                      ],
                      "properties": {
                        "id": {
                          "$id": "#/properties/pages/items/anyOf/0/properties/widgets/items/anyOf/0/properties/visualization/properties/id",
                          "type": "string",
                          "title": "The id of the visualization"
                        }
                      },
                      "additionalProperties": true
                    },
                    "layout": {
                      "$id": "#/properties/pages/items/anyOf/0/properties/widgets/items/anyOf/0/properties/layout",
                      "type": "object",
                      "title": "The layout of the widget",
                      "required": [
                        "column",
                        "row",
                        "height",
                        "width"
                      ],
                      "properties": {
                        "column": {
                          "$id": "#/properties/pages/items/anyOf/0/properties/widgets/items/anyOf/0/properties/layout/properties/column",
                          "type": "integer",
                          "title": "The column position"
                        },
                        "row": {
                          "$id": "#/properties/pages/items/anyOf/0/properties/widgets/items/anyOf/0/properties/layout/properties/row",
                          "type": "integer",
                          "title": "The row position"
                        },
                        "height": {
                          "$id": "#/properties/pages/items/anyOf/0/properties/widgets/items/anyOf/0/properties/layout/properties/height",
                          "type": "integer",
                          "title": "The height"
                        },
                        "width": {
                          "$id": "#/properties/pages/items/anyOf/0/properties/widgets/items/anyOf/0/properties/layout/properties/width",
                          "type": "integer",
                          "title": "The width"
                        }
                      },
                      "additionalProperties": true
                    },
                    "title": {
                      "$id": "#/properties/pages/items/anyOf/0/properties/widgets/items/anyOf/0/properties/title",
                      "type": "string",
                      "title": "The title of the widget"
                    },
                    "rawConfiguration": {
                      "$id": "#/properties/pages/items/anyOf/0/properties/widgets/items/anyOf/0/properties/rawConfiguration",
                      "type": "object",
                      "title": "The configuration of the widget",
                      "oneOf": [
                        {
                          "required": ["nrqlQueries"]
                        },
                        {
                          "required": ["text"]
                        }
                      ],
                      "not": {
                        "required": ["metrics"]
                      },
                      "properties": {
                        "dataFormatters": {
                          "$id": "#/properties/pages/items/anyOf/0/properties/widgets/items/anyOf/0/properties/rawConfiguration/properties/dataFormatters",
                          "type": "array",
                          "title": "Data formatting information",
                          "items": {
                            "$id": "#/properties/pages/items/anyOf/0/properties/widgets/items/anyOf/0/properties/rawConfiguration/properties/dataFormatters/items",
                            "anyOf": [{
                              "$id": "#/properties/pages/items/anyOf/0/properties/widgets/items/anyOf/0/properties/rawConfiguration/properties/dataFormatters/items/anyOf/0",
                              "type": "object",
                              "required": [
                                "name",
                                "type"
                              ],
                              "properties": {
                                "name": {
                                  "$id": "#/properties/pages/items/anyOf/0/properties/widgets/items/anyOf/0/properties/rawConfiguration/properties/dataFormatters/items/anyOf/0/properties/name",
                                  "type": "string"
                                },
                                "type": {
                                  "$id": "#/properties/pages/items/anyOf/0/properties/widgets/items/anyOf/0/properties/rawConfiguration/properties/dataFormatters/items/anyOf/0/properties/type",
                                  "type": "string"
                                }
                              },
                              "additionalProperties": true
                            }]
                          }
                        },
                        "nrqlQueries": {
                          "$id": "#/properties/pages/items/anyOf/0/properties/widgets/items/anyOf/0/properties/rawConfiguration/properties/nrqlQueries",
                          "type": "array",
                          "title": "The NRQL query defined for the widget.",
                          "items": {
                            "$id": "#/properties/pages/items/anyOf/0/properties/widgets/items/anyOf/0/properties/rawConfiguration/properties/nrqlQueries/items",
                            "anyOf": [{
                              "$id": "#/properties/pages/items/anyOf/0/properties/widgets/items/anyOf/0/properties/rawConfiguration/properties/nrqlQueries/items/anyOf/0",
                              "type": "object",
                              "required": [
                                "accountId",
                                "query"
                              ],
                              "properties": {
                                "accountId": {
                                  "$id": "#/properties/pages/items/anyOf/0/properties/widgets/items/anyOf/0/properties/rawConfiguration/properties/nrqlQueries/items/anyOf/0/properties/accountId",
                                  "type": "integer",
                                  "title": "The accountId to get data from",
                                  "minimum": 0,
                                  "maximum": 0
                                },
                                "query": {
                                  "$id": "#/properties/pages/items/anyOf/0/properties/widgets/items/anyOf/0/properties/rawConfiguration/properties/nrqlQueries/items/anyOf/0/properties/query",
                                  "type": "string",
                                  "title": "The query to execute"
                                }
                              },
                              "additionalProperties": true
                            }]
                          }
                        },
                        "text": {
                          "$id": "#/properties/pages/items/anyOf/0/properties/widgets/items/anyOf/0/properties/rawConfiguration/properties/text",
                          "type": "string"
                        },
                        "thresholds": {
                          "$id": "#/properties/pages/items/anyOf/0/properties/widgets/items/anyOf/0/properties/rawConfiguration/properties/thresholds",
                          "type": "array",
                          "items": {
                            "$id": "#/properties/pages/items/anyOf/0/properties/widgets/items/anyOf/0/properties/rawConfiguration/properties/thresholds/items"
                          }
                        }
                      },
                      "additionalProperties": true
                    }
                  },
                  "additionalProperties": true
                }]
              }
            }
          },
          "additionalProperties": true
        }]
      }
    }
  },
  "additionalProperties": false
}

=== newrelic/entity-definitions/definitions/ext-oracle/dashboard.json
{
	"name": "Oracle Database Status",
	"description": null,
	"permissions": "PUBLIC_READ_WRITE",
	"pages": [{
		"name": "Oracle Database Status",
		"description": null,
		"widgets": [{
				"visualization": {
					"id": "viz.table"
				},
				"layout": {
					"column": 1,
					"row": 1,
					"height": 3,
					"width": 7
				},
				"title": "Oracle Server Onboarding ",
				"rawConfiguration": {
					"dataFormatters": [],
					"facet": {
						"showOtherSeries": true
					},
					"nrqlQueries": [{
						"accountId": 0,
						"query": "select latest(timestamp) from Oracle FACET hostname, database, instance_name, instance_mode, database_status SINCE 1 hour ago LIMIT MAX "
					}]
				}
			},
			{
				"visualization": {
					"id": "viz.table"
				},
				"layout": {
					"column": 8,
					"row": 1,
					"height": 3,
					"width": 3
				},
				"title": "Oracle Server Onboarding Status",
				"rawConfiguration": {
					"dataFormatters": [],
					"facet": {
						"showOtherSeries": false
					},
					"nrqlQueries": [{
						"accountId": 0,
						"query": "SELECT latest(timestamp) from Oracle FACET databaseHost LIMIT MAX since 1 hour ago"
					}]
				}
			},
			{
				"visualization": {
					"id": "viz.billboard"
				},
				"layout": {
					"column": 11,
					"row": 1,
					"height": 3,
					"width": 2
				},
				"title": "Oracle Database Host Count",
				"rawConfiguration": {
					"dataFormatters": [],
					"nrqlQueries": [{
						"accountId": 0,
						"query": "SELECT uniqueCount(databaseHost) from Oracle"
					}],
					"thresholds": []
				}
			},
			{
				"visualization": {
					"id": "viz.line"
				},
				"layout": {
					"column": 1,
					"row": 4,
					"height": 3,
					"width": 4
				},
				"title": "Average PGA Allocated ",
				"rawConfiguration": {
					"legend": {
						"enabled": true
					},
					"nrqlQueries": [{
						"accountId": 0,
						"query": "select latest(value) from Oracle where metric_name = 'Total PGA Allocated' facet metric_name, database, hostname   TIMESERIES  limit 1000"
					}],
					"yAxisLeft": {
						"zero": true
					}
				}
			},
			{
				"visualization": {
					"id": "viz.line"
				},
				"layout": {
					"column": 5,
					"row": 4,
					"height": 3,
					"width": 4
				},
				"title": "Avergae User Calls Per Second",
				"rawConfiguration": {
					"dataFormatters": [],
					"legend": {
						"enabled": true
					},
					"nrqlQueries": [{
						"accountId": 0,
						"query": "select latest(value) from Oracle where metric_name = 'User Calls Per Sec'  facet metric_name, database, hostname TIMESERIES    limit 1000"
					}],
					"yAxisLeft": {
						"zero": true
					}
				}
			},
			{
				"visualization": {
					"id": "viz.line"
				},
				"layout": {
					"column": 9,
					"row": 4,
					"height": 3,
					"width": 4
				},
				"title": "Average Temp Space",
				"rawConfiguration": {
					"legend": {
						"enabled": true
					},
					"nrqlQueries": [{
						"accountId": 0,
						"query": "select latest(value) from Oracle where metric_name ='Temp Space Used' facet metric_name, database, hostname   TIMESERIES  limit 1000"
					}],
					"yAxisLeft": {
						"zero": true
					}
				}
			},
			{
				"visualization": {
					"id": "viz.line"
				},
				"layout": {
					"column": 1,
					"row": 7,
					"height": 3,
					"width": 4
				},
				"title": "Average Session Count",
				"rawConfiguration": {
					"dataFormatters": [],
					"legend": {
						"enabled": true
					},
					"nrqlQueries": [{
						"accountId": 0,
						"query": "select latest(value) from Oracle where metric_name = 'Session Count'  facet metric_name, database, hostname TIMESERIES limit 1000"
					}],
					"yAxisLeft": {
						"zero": true
					}
				}
			},
			{
				"visualization": {
					"id": "viz.line"
				},
				"layout": {
					"column": 5,
					"row": 7,
					"height": 3,
					"width": 4
				},
				"title": "Average Cell Physical IO Interconnect Bytes",
				"rawConfiguration": {
					"legend": {
						"enabled": true
					},
					"nrqlQueries": [{
						"accountId": 0,
						"query": "select latest(value) from Oracle where metric_name = 'Cell Physical IO Interconnect Bytes'  facet metric_name, database, hostname   TIMESERIES  limit 1000"
					}],
					"yAxisLeft": {
						"zero": true
					}
				}
			},
			{
				"visualization": {
					"id": "viz.line"
				},
				"layout": {
					"column": 9,
					"row": 7,
					"height": 3,
					"width": 4
				},
				"title": "Average CPU Usage Per Txn",
				"rawConfiguration": {
					"dataFormatters": [],
					"legend": {
						"enabled": true
					},
					"nrqlQueries": [{
						"accountId": 0,
						"query": "select average(value) from Oracle where metric_name = 'CPU Usage Per Txn'  facet metric_name, database, hostname  TIMESERIES 2 minutes   limit 1000"
					}],
					"yAxisLeft": {
						"zero": true
					}
				}
			},
			{
				"visualization": {
					"id": "viz.line"
				},
				"layout": {
					"column": 1,
					"row": 10,
					"height": 3,
					"width": 4
				},
				"title": "Average Response Time Per Txn",
				"rawConfiguration": {
					"dataFormatters": [],
					"legend": {
						"enabled": true
					},
					"nrqlQueries": [{
						"accountId": 0,
						"query": "select average(value) from Oracle where metric_name = 'Response Time Per Txn'  facet metric_name, database, hostname  TIMESERIES   limit 1000"
					}],
					"yAxisLeft": {
						"zero": true
					}
				}
			},
			{
				"visualization": {
					"id": "viz.line"
				},
				"layout": {
					"column": 5,
					"row": 10,
					"height": 3,
					"width": 4
				},
				"title": "Average DB Block Changes per Txn",
				"rawConfiguration": {
					"dataFormatters": [],
					"legend": {
						"enabled": true
					},
					"nrqlQueries": [{
						"accountId": 0,
						"query": "select average(value) from Oracle where metric_name = 'DB Block Changes Per Txn' facet metric_name, database, hostname   TIMESERIES  limit 1000"
					}],
					"yAxisLeft": {
						"zero": true
					}
				}
			},
			{
				"visualization": {
					"id": "viz.line"
				},
				"layout": {
					"column": 9,
					"row": 10,
					"height": 3,
					"width": 4
				},
				"title": "Avg Response Time Per Txn",
				"rawConfiguration": {
					"dataFormatters": [],
					"legend": {
						"enabled": true
					},
					"nrqlQueries": [{
						"accountId": 0,
						"query": "select average(value) from Oracle where metric_name = 'Response Time Per Txn' facet metric_name, database, hostname  TIMESERIES   limit 1000"
					}],
					"yAxisLeft": {
						"zero": true
					}
				}
			},
			{
				"visualization": {
					"id": "viz.line"
				},
				"layout": {
					"column": 1,
					"row": 13,
					"height": 3,
					"width": 4
				},
				"title": "Avg Physical Write Per Txn",
				"rawConfiguration": {
					"dataFormatters": [],
					"legend": {
						"enabled": true
					},
					"nrqlQueries": [{
						"accountId": 0,
						"query": "select average(value) from Oracle where metric_name = 'Physical Writes Per Txn'  facet metric_name, database, hostname TIMESERIES    limit 1000"
					}],
					"yAxisLeft": {
						"zero": true
					}
				}
			},
			{
				"visualization": {
					"id": "viz.line"
				},
				"layout": {
					"column": 5,
					"row": 13,
					"height": 3,
					"width": 4
				},
				"title": "Avg DB wait time ",
				"rawConfiguration": {
					"dataFormatters": [],
					"legend": {
						"enabled": true
					},
					"nrqlQueries": [{
						"accountId": 0,
						"query": "select average(value) from Oracle where metric_name = 'Database Wait Time Ratio'  facet metric_name, database, hostname TIMESERIES  2 minutes limit 1000"
					}],
					"yAxisLeft": {
						"zero": true
					}
				}
			},
			{
				"visualization": {
					"id": "viz.line"
				},
				"layout": {
					"column": 1,
					"row": 16,
					"height": 3,
					"width": 4
				},
				"title": "Avg Physical Write Per Txn",
				"rawConfiguration": {
					"dataFormatters": [],
					"legend": {
						"enabled": true
					},
					"nrqlQueries": [{
						"accountId": 0,
						"query": "select average(value) from Oracle where metric_name = 'Physical Writes Per Txn'  facet metric_name, database, hostname TIMESERIES    limit 1000"
					}],
					"yAxisLeft": {
						"zero": true
					}
				}
			},
			{
				"visualization": {
					"id": "viz.line"
				},
				"layout": {
					"column": 5,
					"row": 16,
					"height": 3,
					"width": 4
				},
				"title": "Avg DB wait time ",
				"rawConfiguration": {
					"dataFormatters": [],
					"legend": {
						"enabled": true
					},
					"nrqlQueries": [{
						"accountId": 0,
						"query": "select average(value) from Oracle where metric_name = 'Database Wait Time Ratio'  facet metric_name, database, hostname TIMESERIES  2 minutes limit 1000"
					}],
					"yAxisLeft": {
						"zero": true
					}
				}
			},
			{
				"visualization": {
					"id": "viz.table"
				},
				"layout": {
					"column": 9,
					"row": 19,
					"height": 3,
					"width": 4
				},
				"title": "Latest Tablespace Usage",
				"rawConfiguration": {
					"dataFormatters": [],
					"facet": {
						"showOtherSeries": false
					},
					"nrqlQueries": [{
						"accountId": 0,
						"query": "select latest(used_percent) from Oracle where queryName = 'Tablespace_metric' facet hostname, databaseHost,tablespace_name, database since 30 minutes ago limit max"
					}]
				}
			}
		]
	}]
}
